export const FETCH_CATEGORIES='FETCH_CATEGORIES';
export const CATEGORIES_LOADING='CATEGORIES_LOADING';
export const CATEGORIES_LOADED='CATEGORIES_LOADED';
export const GET_CATEGORY='GET_CATEGORY';
export const ERROR_CATEGORY='ERROR_CATEGORY';
export const GET_PRODUCTS='GET_PRODUCTS';
export const GET_PRODUCT='GET_PRODUCT';
export const GET_RPRODUCTS='GET_RPRODUCTS';
//cart
export const ADD_CART='ADD_CART';
//check cart
export const CHECK_CART='CHECK_CART';
//fetch cart
export const FETCH_CART='FETCH_CART';
//remove cart
export const REMOVE_CART='REMOVE_CART';
//auth
export const USER_LOADING='USER_LOADING';
export const USER_LOADED='USER_LOADED';
export const AUTH_ERROR='AUTH_ERROR';
export const LOGIN_FAIL='LOGIN_FAIL';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const REGESTER_SUCCESS='REGESTER_SUCCESS';
export const REGESTER_FAIL='REGESTER_FAIL';
export const GET_ERRORS='GET_ERRORS';
export const CLEAR_ERRORS='CLEAR_ERRORS';